language: php

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true

sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction
  # install php extensions
  - |
    if (php --version | grep -i HipHop > /dev/null); then
      echo "Skipping imagick and gmagick tests on HHVM"
    else
      pear config-set preferred_state beta
      printf "\n" | pecl install imagick
      # gmagick is not installed on travis currently
      #printf "\n" | pecl install gmagick
    fi

before_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi

script:
  - phpunit $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
